server:
  port: 8001 #服务端口
#spring相关配置
spring:
  application:
    name: wei-service-payment  #服务名
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name:  com.mysql.cj.jdbc.Driver  #数据库驱动包
#    url: jdbc:mysql://localhost:3306/wei-service?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    url: jdbc:mysql://192.168.101.17:3306/wei-service?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
#mybatis:配置
mybatis-plus:
#  mapperLocations: classpath:mapper/*.xml
#  type-aliases-package: com.buba.springcloud.pojo    # 所有pojo别名类所在包